In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"D:\SCRAPPING_DATA_FROM_AMAZON_task\amazon_laptops_raw_data.csv")
df

,Unnamed: 0,Product Name,Price,Processor,Brand,RAM,Rating,Storage,Windows,Color,Discount,Screen Size
0,0,acer Aspire Lite,"54,999",NaN,ACER,16GB,4.0,512GB,Windows 11,Silver,(31% off),15.6
1,1,Dell 15,"60,526",Intel Core i5,DELL,16GB,3.7,1TB,Windows 11,Silver,(23% off),15.6
2,2,"EBook 11.6"" HD Laptop","10,990",NaN,EBOOK,4GB,4.0,4GB,Windows 11,Black,(56% off),11.6
3,3,HP Chromebook X360 Intel Celeron N4020 14 inch...,"27,990",Intel Celeron,HP,4GB,3.9,4GB,NaN,NaN,(13% off),35.6
4,4,JioBook 11 with Lifetime Office,"10,990",Mediatek,JIOBOOK,4GB,2.9,4GB,NaN,Blue,(56% off),NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
127,127,Acer TravelLite Thin Laptop AMD Ryzen 5 7430U ...,"36,999",AMD Ryzen 5 7430U,ACER,8GB,3.0,512GB,Windows 11,Black,(30% off),14.0
128,128,ASUS Vivobook Go 15,"37,990",AMD Ryzen 5 7520U Thin,ASUS,8GB,4.0,512GB,Windows 11,Silver,(25% off),15.6
129,129,Lenovo ThinkBook 16,"68,490",AMD Ryzen 7 7735HS,LENOVO,16GB,4.3,512GB,Windows 11,NaN,(26% off),16.0
130,130,ASUS Vivobook S14,"65,990",AMD Ryzen AI 5 330,ASUS,16GB,4.4,512GB,Windows 11,Gray,(30% off),14.0
131,131,ASUS Zenbook 14,"85,990",AMD Ryzen AI 5 340,ASUS,16GB,4.2,512GB,Windows 11,Black,(27% off),NaN

In [3]:
df.drop(df.columns[0],axis=1,inplace=True)

In [4]:
df.head()

,Product Name,Price,Processor,Brand,RAM,Rating,Storage,Windows,Color,Discount,Screen Size
0,acer Aspire Lite,"54,999",NaN,ACER,16GB,4.0,512GB,Windows 11,Silver,(31% off),15.6
1,Dell 15,"60,526",Intel Core i5,DELL,16GB,3.7,1TB,Windows 11,Silver,(23% off),15.6
2,"EBook 11.6"" HD Laptop","10,990",NaN,EBOOK,4GB,4.0,4GB,Windows 11,Black,(56% off),11.6
3,HP Chromebook X360 Intel Celeron N4020 14 inch...,"27,990",Intel Celeron,HP,4GB,3.9,4GB,NaN,NaN,(13% off),35.6
4,JioBook 11 with Lifetime Office,"10,990",Mediatek,JIOBOOK,4GB,2.9,4GB,NaN,Blue,(56% off),NaN

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 132 entries, 0 to 131
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Product Name  132 non-null    object
 1   Price         127 non-null    object
 2   Processor     97 non-null     object
 3   Brand         132 non-null    object
 4   RAM           119 non-null    object
 5   Rating        129 non-null    float64
 6   Storage       130 non-null    object
 7   Windows       120 non-null    object
 8   Color         129 non-null    object
 9   Discount      127 non-null    object
 10  Screen Size   115 non-null    float64
dtypes: float64(2), object(9)
memory usage: 11.5+ KB

In [6]:
df.shape

(132, 11)

In [7]:
df.isna().sum()

Product Name     0
Price            5
Processor       35
Brand            0
RAM             13
Rating           3
Storage          2
Windows         12
Color            3
Discount         5
Screen Size     17
dtype: int64

In [8]:
df.drop_duplicates()

,Product Name,Price,Processor,Brand,RAM,Rating,Storage,Windows,Color,Discount,Screen Size
0,acer Aspire Lite,"54,999",NaN,ACER,16GB,4.0,512GB,Windows 11,Silver,(31% off),15.6
1,Dell 15,"60,526",Intel Core i5,DELL,16GB,3.7,1TB,Windows 11,Silver,(23% off),15.6
2,"EBook 11.6"" HD Laptop","10,990",NaN,EBOOK,4GB,4.0,4GB,Windows 11,Black,(56% off),11.6
3,HP Chromebook X360 Intel Celeron N4020 14 inch...,"27,990",Intel Celeron,HP,4GB,3.9,4GB,NaN,NaN,(13% off),35.6
4,JioBook 11 with Lifetime Office,"10,990",Mediatek,JIOBOOK,4GB,2.9,4GB,NaN,Blue,(56% off),NaN
...,...,...,...,...,...,...,...,...,...,...,...
126,Lenovo IdeaPad Slim 3 AMD Ryzen 7 8840HS 15.3 ...,"67,490",AMD Ryzen 7 8840HS 15,LENOVO,16GB,4.8,512GB,Windows 11,Grey,(29% off),38.8
127,Acer TravelLite Thin Laptop AMD Ryzen 5 7430U ...,"36,999",AMD Ryzen 5 7430U,ACER,8GB,3.0,512GB,Windows 11,Black,(30% off),14.0
128,ASUS Vivobook Go 15,"37,990",AMD Ryzen 5 7520U Thin,ASUS,8GB,4.0,512GB,Windows 11,Silver,(25% off),15.6
129,Lenovo ThinkBook 16,"68,490",AMD Ryzen 7 7735HS,LENOVO,16GB,4.3,512GB,Windows 11,NaN,(26% off),16.0
131,ASUS Zenbook 14,"85,990",AMD Ryzen AI 5 340,ASUS,16GB,4.2,512GB,Windows 11,Black,(27% off),NaN

In [9]:
df["Price"]=df["Price"].astype(str).str.replace(",","",regex=False).str.strip()
df["Price"]=pd.to_numeric(df["Price"],errors="coerce")
df["Price"]

0      54999.0
1      60526.0
2      10990.0
3      27990.0
4      10990.0
        ...
127    36999.0
128    37990.0
129    68490.0
130    65990.0
131    85990.0
Name: Price, Length: 132, dtype: float64

In [10]:
df["Discount"] = (df["Discount"].astype(str).str.replace(r"[()%]", "", regex=True).str.replace("off", "", regex=False).str.strip())
df["Discount"] = pd.to_numeric(df["Discount"], errors="coerce")
df["Discount"]

0      31.0
1      23.0
2      56.0
3      13.0
4      56.0
       ...
127    30.0
128    25.0
129    26.0
130    30.0
131    27.0
Name: Discount, Length: 132, dtype: float64

In [11]:
df.to_csv("amazon_laptop_cleaned.csv")