In [1]:
import pandas as pd

In [3]:
df = pd.read_csv(r"D:\SCRAPPING_DATA_FROM_AMAZON_task\amazon_laptop_cleaned.csv")
df

,Unnamed: 0,Product Name,Price,Processor,Brand,RAM,Rating,Storage,Windows,Color,Discount,Screen Size
0,0,acer Aspire Lite,54999.0,NaN,ACER,16GB,4.0,512GB,Windows 11,Silver,31.0,15.6
1,1,Dell 15,60526.0,Intel Core i5,DELL,16GB,3.7,1TB,Windows 11,Silver,23.0,15.6
2,2,"EBook 11.6"" HD Laptop",10990.0,NaN,EBOOK,4GB,4.0,4GB,Windows 11,Black,56.0,11.6
3,3,HP Chromebook X360 Intel Celeron N4020 14 inch...,27990.0,Intel Celeron,HP,4GB,3.9,4GB,NaN,NaN,13.0,35.6
4,4,JioBook 11 with Lifetime Office,10990.0,Mediatek,JIOBOOK,4GB,2.9,4GB,NaN,Blue,56.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
127,127,Acer TravelLite Thin Laptop AMD Ryzen 5 7430U ...,36999.0,AMD Ryzen 5 7430U,ACER,8GB,3.0,512GB,Windows 11,Black,30.0,14.0
128,128,ASUS Vivobook Go 15,37990.0,AMD Ryzen 5 7520U Thin,ASUS,8GB,4.0,512GB,Windows 11,Silver,25.0,15.6
129,129,Lenovo ThinkBook 16,68490.0,AMD Ryzen 7 7735HS,LENOVO,16GB,4.3,512GB,Windows 11,NaN,26.0,16.0
130,130,ASUS Vivobook S14,65990.0,AMD Ryzen AI 5 330,ASUS,16GB,4.4,512GB,Windows 11,Gray,30.0,14.0
131,131,ASUS Zenbook 14,85990.0,AMD Ryzen AI 5 340,ASUS,16GB,4.2,512GB,Windows 11,Black,27.0,NaN

In [4]:
# 1. Which brand has highest average price?

highest_avg_price=df.groupby("Brand")["Price"].mean().sort_values(ascending=False)
res=highest_avg_price.reset_index(name="Average Price")
res

         Brand  Average Price
0    MICROSOFT  243990.000000
1        APPLE  127195.000000
2          MSI   97101.666667
3           HP   79182.360000
4       LENOVO   78891.709677
5         ASUS   69880.800000
6         ACER   55745.250000
7      SAMSUNG   54800.000000
8         DELL   54429.214286
9       IENOVO   25995.000000
10     ULTIMUS   18990.000000
11     THOMSON   15240.000000
12  BROWSEBOOK   12990.000000
13       EBOOK   10990.000000
14     JIOBOOK   10990.000000
15      STRIFF     199.000000

In [5]:
# 2. Which brand has highest average rating?

highest_avg_rating=df.groupby("Brand")["Rating"].mean().sort_values(ascending=False)
res=highest_avg_rating.reset_index(name="Average Rating")
res

         Brand  Average Rating
0      SAMSUNG        4.900000
1        APPLE        4.750000
2         ASUS        4.216000
3       STRIFF        4.200000
4          MSI        4.166667
5       LENOVO        4.139394
6        EBOOK        4.000000
7           HP        3.961538
8         DELL        3.878571
9         ACER        3.866667
10     THOMSON        3.800000
11     ULTIMUS        3.400000
12  BROWSEBOOK        3.000000
13     JIOBOOK        2.900000
14   MICROSOFT        2.900000
15      IENOVO             NaN

In [6]:
# 3. Top 5 most reviewed laptops?

most_reviewed_lap = (df.sort_values("Rating", ascending=False).head(5))
most_reviewed_lap

,Unnamed: 0,Product Name,Price,Processor,Brand,RAM,Rating,Storage,Windows,Color,Discount,Screen Size
84,84,ASUS Vivobook 15 (2025),37990.0,Intel Core i3-1315U,ASUS,8GB,5.0,512GB,Windows 11,Silver,25.0,15.6
29,29,Thomson NEO 14.1 Inch IN-P14C Intel Dual Core ...,14990.0,NaN,THOMSON,8GB,5.0,256GB,NaN,White,46.0,NaN
63,63,HP Professional 14 (2025),43950.0,Intel Core i3,HP,NaN,5.0,512GB,Windows 11,Silver,21.0,14.0
26,26,ASUS Gaming V16 (2025),99990.0,NaN,ASUS,16GB,5.0,512GB,Windows 11,Black,28.0,16.0
25,25,DELL 14 (2026) Intel Core 3 14th Gen 100U - (1...,44790.0,NaN,DELL,16GB,5.0,512GB,Windows 11,Blue,32.0,14.0

In [7]:
# 5. Price vs Rating correlation value?

res=df["Price"].corr(df["Rating"])
res

# As price increases, rating slightly decreases,
# BUT the relationship is very weak.
# Because:
# Correlation is close to 0
# Not close to -1

np.float64(-0.015933185213693496)

In [8]:
# 6. Distribution of laptops by RAM (8GB, 16GB, etc.)

df["RAM"] = df["RAM"].str.upper().str.strip()
distributions_on_brand=df["RAM"].value_counts().reset_index(name="Number of Laptops")
distributions_on_brand

    RAM  Number of Laptops
0  16GB                 73
1   8GB                 17
2  24GB                 16
3   4GB                  7
4  32GB                  3
5  12GB                  2
6   6GB                  1

In [9]:
# 7. Which screen size is most common?

df["Screen Size"].value_counts().idxmax()

np.float64(15.6)

In [10]:
# 8. How many laptops under ₹50,000?

res = df[df["Price"]<50000]
res.count()

Unnamed: 0      37
Product Name    37
Price           37
Processor       27
Brand           37
RAM             34
Rating          36
Storage         35
Windows         28
Color           35
Discount        37
Screen Size     25
dtype: int64

In [11]:
# 9. What is the average price by RAM configuration (8GB vs 16GB vs 32GB)?

res=df.groupby("RAM")["Price"].mean().reset_index(name="Average Price")
res

    RAM  Average Price
0  12GB   41895.000000
1  16GB   68969.958333
2  24GB  107633.750000
3  32GB  199323.333333
4   4GB   17406.666667
5   6GB   62990.000000
6   8GB   29975.533333

In [12]:
# 10. What is the average price by processor type (i3, i5, Ryzen 5, etc.)?

res=df.groupby("Processor")["Price"].mean().reset_index(name="Average Price")
res

                                        Processor  Average Price
0   AMD Athlon Silver 7120U Laptop 8GB LPDDR5 Ram   34999.000000
1                               AMD Ryzen 3 7320U   36370.000000
2                               AMD Ryzen 5 7430U   36999.000000
3                               AMD Ryzen 5 7520U   45990.000000
4                            AMD Ryzen 5 7520U 15   41890.000000
5                        AMD Ryzen 5 7520U DOS 15   42799.000000
6                          AMD Ryzen 5 7520U Thin   37990.000000
7                                     AMD Ryzen 7   63240.000000
8                               AMD Ryzen 7 5825U   49490.000000
9                              AMD Ryzen 7 7445HS   72492.250000
10                           AMD Ryzen 7 7730U 15   52999.000000
11                             AMD Ryzen 7 7735HS   68490.000000
12                             AMD Ryzen 7 7840Hs  126220.000000
13                          AMD Ryzen 7 8840HS 15   76061.428571
14                             AMD Ryzen 9 8940HX  158990.000000
15                             AMD Ryzen AI 5 330   64275.714286
16                             AMD Ryzen AI 5 340   85990.000000
17                             AMD Ryzen AI 7 350   95323.333333
18                                       Apple M4   89900.000000
19                                  Intel Celeron   20490.000000
20                                  Intel Core i3   43470.000000
21                            Intel Core i3-1215U   37990.000000
22                            Intel Core i3-1315U   39854.000000
23                                  Intel Core i5   59470.250000
24                           Intel Core i5-12450H   51375.000000
25                            Intel Core i5-1335U   66240.000000
26                       Intel Core i5-1335U-13th   55990.000000
27                           Intel Core i5-13420H   62990.000000
28                          Intel Core i5-14450HX   80490.000000
29                                  Intel Core i7   90332.333333
30                            Intel Core i7-1355U   67990.000000
31                           Intel Core i7-13620H  112740.000000
32                          Intel Core i7-14650HX  138990.000000
33                          Intel Core i9-14900HX  164490.000000
34                                  Intel Pentium   18990.000000
35                                       Mediatek   10990.000000
36                            Qualcomm Snapdragon  243990.000000

In [13]:
# 11. What is the price distribution (budget, mid-range, premium)?

df["Price_Category"] = pd.cut(
    df["Price"],
    bins=[0, 40000, 70000, float("inf")],
    labels=["Budget", "Mid-Range", "Premium"]
)
df

,Unnamed: 0,Product Name,Price,Processor,Brand,RAM,Rating,Storage,Windows,Color,Discount,Screen Size,Price_Category
0,0,acer Aspire Lite,54999.0,NaN,ACER,16GB,4.0,512GB,Windows 11,Silver,31.0,15.6,Mid-Range
1,1,Dell 15,60526.0,Intel Core i5,DELL,16GB,3.7,1TB,Windows 11,Silver,23.0,15.6,Mid-Range
2,2,"EBook 11.6"" HD Laptop",10990.0,NaN,EBOOK,4GB,4.0,4GB,Windows 11,Black,56.0,11.6,Budget
3,3,HP Chromebook X360 Intel Celeron N4020 14 inch...,27990.0,Intel Celeron,HP,4GB,3.9,4GB,NaN,NaN,13.0,35.6,Budget
4,4,JioBook 11 with Lifetime Office,10990.0,Mediatek,JIOBOOK,4GB,2.9,4GB,NaN,Blue,56.0,NaN,Budget
...,...,...,...,...,...,...,...,...,...,...,...,...,...
127,127,Acer TravelLite Thin Laptop AMD Ryzen 5 7430U ...,36999.0,AMD Ryzen 5 7430U,ACER,8GB,3.0,512GB,Windows 11,Black,30.0,14.0,Budget
128,128,ASUS Vivobook Go 15,37990.0,AMD Ryzen 5 7520U Thin,ASUS,8GB,4.0,512GB,Windows 11,Silver,25.0,15.6,Budget
129,129,Lenovo ThinkBook 16,68490.0,AMD Ryzen 7 7735HS,LENOVO,16GB,4.3,512GB,Windows 11,NaN,26.0,16.0,Mid-Range
130,130,ASUS Vivobook S14,65990.0,AMD Ryzen AI 5 330,ASUS,16GB,4.4,512GB,Windows 11,Gray,30.0,14.0,Mid-Range
131,131,ASUS Zenbook 14,85990.0,AMD Ryzen AI 5 340,ASUS,16GB,4.2,512GB,Windows 11,Black,27.0,NaN,Premium